#!/usr/bin/env python3
"""Generate Codex TOML agent definitions from canonical Claude Markdown files."""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path


AGENTS_DIR = Path(__file__).resolve().parents[1] / "agents"
FRONTMATTER_RE = re.compile(r"\A---\n(?P<header>.*?)\n---\n(?P<body>.*)\Z", re.DOTALL)


def parse_agent(path: Path) -> tuple[str, str, str]:
    match = FRONTMATTER_RE.match(path.read_text())
    if not match:
        raise ValueError(f"{path}: expected YAML frontmatter")

    header = match.group("header")
    name_match = re.search(r"^name:\s*(.+?)\s*$", header, re.MULTILINE)
    description_match = re.search(
        r"^description:\s*>-?\s*\n(?P<value>(?:^[ \t]+.*\n?)+)",
        header,
        re.MULTILINE,
    )
    if not name_match or not description_match:
        raise ValueError(f"{path}: expected name and folded description fields")

    description_lines = [line.strip() for line in description_match.group("value").splitlines()]
    description = " ".join(line for line in description_lines if line)
    return name_match.group(1).strip(), description, match.group("body").rstrip() + "\n"


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def render(path: Path) -> str:
    name, description, instructions = parse_agent(path)
    if "'''" in instructions:
        raise ValueError(f"{path}: body contains TOML multiline-string delimiter")
    return (
        "# Generated by ../scripts/sync_agent_shims.py; edit the matching .md file.\n"
        f"name = {toml_string(name)}\n"
        f"description = {toml_string(description)}\n"
        "developer_instructions = '''\n"
        f"{instructions}"
        "'''\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale: list[Path] = []
    for source in sorted(AGENTS_DIR.glob("*.md")):
        target = source.with_suffix(".toml")
        generated = render(source)
        tomllib.loads(generated)
        if target.exists() and target.read_text() == generated:
            continue
        if args.check:
            stale.append(target)
        else:
            target.write_text(generated)

    if stale:
        print("Stale Codex agent shims:")
        for path in stale:
            print(f"  {path.relative_to(AGENTS_DIR.parent.parent)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
